import {
  Activity,
  ShoppingCart,
  Receipt,
  Wallet,
  Package,
  Users,
  Percent,
  BarChart3,
  Building2,
  User,
  Settings,
  LogOut,
  Sun,
  Moon,
  X,
  Menu,
  Check,
  AlertCircle,
  FileText,
  Layers,
  Banknote,
  CreditCard,
  Edit2,
  Trash2,
  Search,
  Plus,
  RefreshCw,
  Gift,
  HelpCircle,
  Globe,
  Store,
  ChevronLeft,
  ChevronRight,
  Eye,
  Eraser,
  Printer,
  ChevronDown,
  Info
} from 'lucide-react';

export const AppIcons = {
  dashboard: Activity,
  pos: ShoppingCart,
  sales: Receipt,
  expenses: Wallet,
  inventory: Package,
  customers: Users,
  discounts: Percent,
  reports: BarChart3,
  suppliers: Building2,
  users: User,
  settings: Settings,
  logout: LogOut,
  
  // Theme
  sun: Sun,
  moon: Moon,
  
  // Common Utilities
  close: X,
  menu: Menu,
  check: Check,
  alert: AlertCircle,
  info: Info,
  file: FileText,
  layers: Layers,
  cash: Banknote,
  card: CreditCard,
  edit: Edit2,
  delete: Trash2,
  search: Search,
  plus: Plus,
  sync: RefreshCw,
  gift: Gift,
  help: HelpCircle,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  eye: Eye,
  eraser: Eraser,
  printer: Printer,
  chevronDown: ChevronDown,
  
  // Sale types
  retail: Store,
  wholesale: Package,
  estore: Globe
};
