import React from 'react';
import { PackageOpen, Trash2 } from 'lucide-react';
import { EmptyState, Badge, Pagination, Button } from '../../shared/ui';
import { formatCurrency, getCurrencySymbol } from '../../lib/currencies';
import type { PurchaseOrderFormTableProps } from './PurchaseOrderForm.types';

const ITEMS_PER_PAGE = 25;

export function PurchaseOrderFormTable({
  activeList,
  totalItemsNeeded,
  paginatedList,
  totalPages,
  currentPage,
  setCurrentPage,
  isAdmin,
  isGenerated,
  poMode,
  selectedSupplier,
  selectedCategory,
  estimatedCost,
  appSettings,
  updateItem,
  handleRemoveFromPO,
  removeFromManualList
}: PurchaseOrderFormTableProps) {
  return (
    <div className="bg-white dark:bg-surface rounded-[3rem] border border-gray-200 dark:border-white/5 overflow-hidden shadow-2xl print:shadow-none print:border-none print:rounded-none">
      <div className="hidden print:block p-8 border-b border-black/20">
        <div className="flex justify-between items-start">
          <div>
            <h1 className="text-3xl font-black uppercase mb-1">{"PURCHASE ORDER"}</h1>
            <p className="text-sm text-gray-600">{"Supplier"}: <span className="font-bold text-gray-900">{selectedSupplier}</span></p>
            <p className="text-sm text-gray-600">{"Category"}: <span className="font-bold text-gray-900">{selectedCategory}</span></p>
          </div>
          <div className="text-right">
            <p className="text-sm font-bold">{"Date"}: {new Date().toLocaleDateString()}</p>
            <p className="text-xs text-gray-600 mt-1">Generated by POS</p>
          </div>
        </div>
        <div className="mt-8 flex justify-between w-2/3 border-t border-black/10 pt-4">
          <div>
            <p className="text-xs text-gray-600 uppercase">{"Total Items Required"}</p>
            <p className="text-lg font-black">{totalItemsNeeded.toLocaleString()}</p>
          </div>
          <div>
            <p className="text-xs text-gray-600 uppercase">{"Est. Financial Need"}</p>
            <p className="text-lg font-black">{formatCurrency(estimatedCost, appSettings.currency)}</p>
          </div>
        </div>
      </div>
      <div className="overflow-x-auto">
        {activeList.length === 0 ? (
          <EmptyState
            icon={<PackageOpen className="h-full w-full opacity-20 text-primary" />}
            title={poMode === 'manual' ? "NO ITEMS SELECTED YET" : "INVENTORY IS HEALTHY"}
            subtext={poMode === 'manual'
              ? "SEARCH PRODUCTS ABOVE AND CLICK THE PLUS ICON TO ADD THEM TO YOUR ORDER"
              : "ALL ITEMS ARE CURRENTLY ABOVE THEIR DEFINED REORDER LEVELS"}
            className="!py-20"
          />
        ) : (
          <table className="w-full text-left border-collapse print:text-[10px]">
            <thead>
              <tr className="bg-gray-50/50 dark:bg-white/[0.02] print:bg-transparent">
                <th className="p-8 print:p-2 text-[11px] print:text-[10px] font-black uppercase text-gray-600 tracking-[0.2em] border-b border-gray-200 dark:border-white/5 print:border-black/20">{"Item / SKU"}</th>
                <th className="p-8 print:p-2 text-[11px] print:text-[10px] font-black uppercase text-gray-600 tracking-[0.2em] text-center border-b border-gray-200 dark:border-white/5 print:border-black/20">{"Supplier"}</th>
                <th className="p-8 print:p-2 text-[11px] print:text-[10px] font-black uppercase text-gray-600 tracking-[0.2em] text-center border-b border-gray-200 dark:border-white/5 print:border-black/20">{"Current"}</th>
                <th className="p-8 print:p-2 text-[11px] print:text-[10px] font-black uppercase text-primary dark:text-emerald-400 tracking-[0.2em] text-center bg-emerald-50/50 dark:bg-primary/5 print:bg-transparent border-b border-gray-200 dark:border-white/5 print:border-black/20">{"Qty"}</th>
                <th className="p-8 print:p-2 text-[11px] print:text-[10px] font-black uppercase text-gray-600 tracking-[0.2em] text-right border-b border-gray-200 dark:border-white/5 print:border-black/20">{"Cost"} ({getCurrencySymbol(appSettings.currency)})</th>
                <th className="p-8 print:p-2 text-[11px] print:text-[10px] font-black uppercase text-emerald-400 tracking-[0.2em] text-right border-b border-gray-200 dark:border-white/5 print:border-black/20">{"Retail"} ({getCurrencySymbol(appSettings.currency)})</th>
                <th className="p-8 print:p-2 text-[11px] print:text-[10px] font-black uppercase text-gray-600 tracking-[0.2em] text-right border-b border-gray-200 dark:border-white/5 print:border-black/20">{"Total"} ({getCurrencySymbol(appSettings.currency)})</th>
                {isAdmin && <th className="p-8 print:p-2 text-[11px] print:text-[10px] font-black uppercase text-gray-600 tracking-[0.2em] text-right border-b print:border-black/20 print:hidden">{"Ops"}</th>}
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-50 dark:divide-white/5 print:divide-black/10">
              {paginatedList.map(item => (
                <tr key={item.id} className="group hover:bg-gray-50/50 dark:hover:bg-white/[0.01] transition-all duration-300 print:break-inside-avoid">
                  <td className="p-8 print:p-2">
                    <p className="font-black text-gray-900 dark:text-white text-[13px] uppercase tracking-tight">{item.name}</p>
                    <p className="text-[10px] font-bold text-gray-600 dark:text-gray-400 tracking-widest mt-1">{item.sku || 'No SKU'}</p>
                  </td>
                  <td className="p-8 print:p-2 text-center">
                    <input
                      type="text"
                      disabled={isGenerated}
                      value={item.supplier || ''}
                      onChange={(e) => updateItem(item.id, 'supplier', e.target.value)}
                      placeholder="Supplier"
                      className={`w-full max-w-[120px] bg-gray-50 dark:bg-white/5 border-none text-center rounded-xl font-bold text-[10px] uppercase p-2 focus:ring-1 focus:ring-emerald-500 placeholder:opacity-30 ${isGenerated ? 'opacity-50 cursor-not-allowed' : ''}`}
                    />
                  </td>
                  <td className="p-8 print:p-2 text-center">
                    <Badge
                      tone={item.stock <= 0 ? 'danger' : 'neutral'}
                      size="md"
                      className={`!px-3 !py-1 !rounded-lg !text-xs ${item.stock <= 0 ? '!bg-rose-100 !text-rose-700 dark:!bg-rose-500/20 dark:!text-rose-400' : '!bg-gray-100 !text-gray-700 dark:!bg-white/10 dark:!text-gray-300'}`}
                    >
                      {item.stock}
                    </Badge>
                  </td>
                  <td className="p-8 print:p-2 text-center">
                    <input
                      type="number"
                      value={item.neededQty}
                      onChange={(e) => updateItem(item.id, 'neededQty', Number(e.target.value))}
                      className="w-20 bg-emerald-50 dark:bg-primary/10 border-none text-center rounded-xl font-black text-primary p-2 focus:ring-1 focus:ring-emerald-500"
                    />
                  </td>
                  <td className="p-8 print:p-2 text-right">
                    <input
                      type="number"
                      value={item.cost}
                      onChange={(e) => updateItem(item.id, 'cost', Number(e.target.value))}
                      className="w-24 bg-gray-50 dark:bg-white/5 border-none text-right rounded-xl font-black text-gray-700 dark:text-gray-300 p-2 focus:ring-1 focus:ring-emerald-500"
                    />
                  </td>
                  <td className="p-8 print:p-2 text-right">
                    <input
                      type="number"
                      value={item.price}
                      onChange={(e) => updateItem(item.id, 'price', Number(e.target.value))}
                      className="w-24 bg-emerald-50 dark:bg-primary/5 border-none text-right rounded-xl font-black text-primary dark:text-emerald-400 p-2 focus:ring-1 focus:ring-emerald-500"
                    />
                  </td>
                  <td className="p-8 print:p-2 text-right text-sm font-black text-gray-900 dark:text-white tracking-tight">
                    {formatCurrency(Number(item.neededQty || 0) * Number(item.cost || 0), appSettings.currency)}
                  </td>
                  {isAdmin && (
                    <td className="p-8 print:p-2 text-right print:hidden">
                      <Button
                        onClick={() => poMode === 'manual' ? removeFromManualList(item.id) : handleRemoveFromPO(item.id, item.name)}
                        variant="ghost"
                        className="!min-h-0 !p-3 !bg-rose-50 dark:!bg-rose-500/10 !text-rose-500 !rounded-[1.2rem] lg:opacity-0 group-hover:opacity-100 hover:!bg-rose-100 dark:hover:!bg-rose-500/20 hover:!scale-110 !shadow-sm"
                        title={poMode === 'manual' ? 'Remove from Selection' : 'Clear Target Level'}
                        icon={<Trash2 className="h-4 w-4" />}
                      />
                    </td>
                  )}
                </tr>
              ))}

              <tr className="font-black text-sm bg-gray-50/30 dark:bg-white/[0.01]">
                <td colSpan={6} className="text-right p-8 uppercase tracking-widest text-[11px] text-gray-600 border-t border-gray-200 dark:border-white/5">{"Order Estimated Total:"}</td>
                <td className="text-right p-8 text-xl tracking-tight text-primary dark:text-emerald-400 border-t border-gray-200 dark:border-white/5">{formatCurrency(estimatedCost, appSettings.currency)}</td>
                <td className="print:hidden border-t border-gray-200 dark:border-white/5"></td>
              </tr>
            </tbody>
          </table>
        )}
      </div>

      {totalPages > 1 && (
        <div className="print-hide p-6 bg-gray-50/30 dark:bg-white/[0.01] border-t border-gray-200 dark:border-white/5 flex items-center justify-between">
          <p className="text-[11px] font-black text-gray-600 uppercase tracking-[0.2em]">
            {"Showing"} <span className="text-primary">{((currentPage - 1) * ITEMS_PER_PAGE) + 1}</span> - <span className="text-primary">{Math.min(currentPage * ITEMS_PER_PAGE, activeList.length)}</span> {"of"} <span className="text-primary">{activeList.length}</span> {"items"}
          </p>
          <div className="flex items-center gap-1.5 mx-auto sm:mx-0">
            <Pagination
              mode="prevNext"
              page={currentPage}
              totalPages={totalPages}
              totalItems={activeList.length}
              onPageChange={setCurrentPage}
              pageSize={ITEMS_PER_PAGE}
            />
          </div>
        </div>
      )}
    </div>
  );
}
