import {
  Bundle,
  BundleItem,
} from '../../types';

export const mapBundle = (row: any): Bundle => ({
  id: row.id,
  name: row.name || '',
  description: row.description || '',
  discountValue: Number(row.discount_value) || 0,
  discountType: row.discount_type || 'percentage',
  active: row.active !== false,
  scheduleType: row.schedule_type || 'always',
  startDate: row.start_date || undefined,
  endDate: row.end_date || undefined,
  repeatDays: row.repeat_days || undefined,
  startTime: row.start_time || undefined,
  endTime: row.end_time || undefined,
  hideItemPrices: row.hide_item_prices === true,
  image: row.image,
  extraToppings: (row.extra_toppings as any) || [],
  items: (row.bundle_items || []).map((bi: any): BundleItem => ({
    id: bi.id,
    bundleId: bi.bundle_id,
    productId: bi.product_id,
    quantity: Number(bi.quantity) || 1,
    createdAt: bi.created_at ? new Date(bi.created_at) : new Date(),
  })),
  isCombo: row.is_combo === true,
  dealCategory: row.deal_category || 'pizza',
  overridePrice: row.override_price ? Number(row.override_price) : undefined,
  highlightTag: row.highlight_tag ?? row.highlightTag,
  badgeEnabled: row.badge_enabled === true,
  badgeText: row.badge_text || undefined,
  badgeIcon: row.badge_icon || undefined,
  badgeBgColor: row.badge_bg_color || undefined,
  badgeTextColor: row.badge_text_color || undefined,
  slots: (row.bundle_slots || []).map((s: any) => ({
    id: s.id,
    bundleId: s.bundle_id,
    name: s.name,
    requiredQuantity: s.required_quantity,
    orderIndex: s.order_index,
    options: (s.bundle_slot_options || [])
      .map((o: any) => ({
        id: o.id,
        slotId: o.slot_id,
        productId: o.product_id,
        sortOrder: o.sort_order ?? 0,
      }))
      .sort((a: any, b: any) => (a.sortOrder ?? 0) - (b.sortOrder ?? 0)),
  })),
  createdAt: row.created_at ? new Date(row.created_at) : new Date(),
  updatedAt: row.updated_at ? new Date(row.updated_at) : new Date(),
});
